services:
  redis:
    image: redis:alpine
    container_name: database
    command: redis-server --requirepass ${PASSWORD_REDIS}
    ports:
      - "6379:6379"
    env_file:
      - .env

  app:
    build: .
    container_name: rate_limiter
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis